In [1]:
import numpy as np

In [10]:
x = np.ceil(np.random.random([8,8])*10)
x

array([[ 2.,  8.,  9.,  7.,  3.,  6.,  6.,  9.],
       [10.,  8.,  6.,  8.,  4.,  4., 10.,  5.],
       [ 5.,  2.,  5.,  6.,  1.,  7.,  6.,  4.],
       [10.,  1., 10.,  8.,  7.,  3.,  5.,  9.],
       [ 3.,  8.,  3., 10.,  1.,  4.,  7.,  9.],
       [ 9.,  5.,  8.,  1.,  7.,  3.,  9.,  9.],
       [ 8.,  3.,  5.,  9.,  9.,  9.,  3.,  7.],
       [ 2.,  1., 10.,  8.,  3.,  7.,  9.,  5.]])

In [14]:
x1,x2 = np.split(x, 2)
np.concatenate([x1,x2])

array([[ 2.,  8.,  9.,  7.,  3.,  6.,  6.,  9.],
       [10.,  8.,  6.,  8.,  4.,  4., 10.,  5.],
       [ 5.,  2.,  5.,  6.,  1.,  7.,  6.,  4.],
       [10.,  1., 10.,  8.,  7.,  3.,  5.,  9.],
       [ 3.,  8.,  3., 10.,  1.,  4.,  7.,  9.],
       [ 9.,  5.,  8.,  1.,  7.,  3.,  9.,  9.],
       [ 8.,  3.,  5.,  9.,  9.,  9.,  3.,  7.],
       [ 2.,  1., 10.,  8.,  3.,  7.,  9.,  5.]])

In [17]:
x1,x2 = np.split(x, 2, axis=1)
np.concatenate([x1,x2], axis=1)

array([[ 2.,  8.,  9.,  7.,  3.,  6.,  6.,  9.],
       [10.,  8.,  6.,  8.,  4.,  4., 10.,  5.],
       [ 5.,  2.,  5.,  6.,  1.,  7.,  6.,  4.],
       [10.,  1., 10.,  8.,  7.,  3.,  5.,  9.],
       [ 3.,  8.,  3., 10.,  1.,  4.,  7.,  9.],
       [ 9.,  5.,  8.,  1.,  7.,  3.,  9.,  9.],
       [ 8.,  3.,  5.,  9.,  9.,  9.,  3.,  7.],
       [ 2.,  1., 10.,  8.,  3.,  7.,  9.,  5.]])