In [1]:
import numpy as np

In [18]:
a = np.random.choice(np.arange(0,10),size=(2,2))
b = np.random.choice(np.arange(0,10),size=(2,2))
a += np.transpose(a)
b += np.transpose(b)
c = np.dot(a,b)
c

array([[152, 188],
       [184, 240]])

In [20]:
eigen = np.linalg.eigvals(c)
eigen

array([  4.87700295, 387.12299705])

In [43]:
a = np.arange(0, 10, 1)
ind = np.array([1, 1, 0, 4])
b = a[ind]
m = a%2==0
a[m]
c = np.array(['ssssas','sssssad'])

In [40]:
a.itemsize

8

In [48]:
X = np.random.random((5, 3))
X

array([[0.08624888, 0.80583343, 0.43325801],
       [0.871335  , 0.30438193, 0.323171  ],
       [0.40625548, 0.59449746, 0.67628908],
       [0.32371389, 0.54872621, 0.3489287 ],
       [0.34969926, 0.82530833, 0.03982752]])

In [50]:
X[:, np.newaxis, :] -X

array([[[ 0.        ,  0.        ,  0.        ],
        [-0.78508612,  0.5014515 ,  0.110087  ],
        [-0.32000661,  0.21133597, -0.24303107],
        [-0.23746502,  0.25710722,  0.08432931],
        [-0.26345038, -0.01947489,  0.39343048]],

       [[ 0.78508612, -0.5014515 , -0.110087  ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.46507952, -0.29011552, -0.35311807],
        [ 0.5476211 , -0.24434428, -0.02575769],
        [ 0.52163574, -0.52092639,  0.28334348]],

       [[ 0.32000661, -0.21133597,  0.24303107],
        [-0.46507952,  0.29011552,  0.35311807],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.08254159,  0.04577125,  0.32736038],
        [ 0.05655622, -0.23081087,  0.63646155]],

       [[ 0.23746502, -0.25710722, -0.08432931],
        [-0.5476211 ,  0.24434428,  0.02575769],
        [-0.08254159, -0.04577125, -0.32736038],
        [ 0.        ,  0.        ,  0.        ],
        [-0.02598537, -0.27658212,  0.30910117]],

       [[ 0.